### ISSUE TITLE
svymultinom and negative df.residual

### ISSUE THREAD

**Issue by larmarange** [carlganz/svrepmisc#3]
Dear @carlganz,

When you have a svrepdesign with not enough replicates, a call to `svymultinom ` or similar function will result with a negative number of `df.residual` resulting with an impossibility to compute confidance intervals using t distribution.

Would consider to add a specific warning in `wR` to inform user?

**Comment by carlganz** [comment]
Hello,

I am pretty surprised (in a good way) to discover that another human is using this package. I don't believe I spent sufficient time ensuring that this package generates statistically accurate results, so I urge you to please use this package with caution.

I am not actively supporting this package, if you would like to make a pull request to add a warning I will gladly merge it.

Kind Regards

**Comment by larmarange** [comment]
Dear @carlganz ,

thank you very much for your feedback. I'm facing the need for multinomial and ordinal (clm) models with complex survey data and to be honest there are very few explanations online.

The only detailed other example I found online was https://rpubs.com/corey_sparks/249896 but it seems that there is a mistake as the author is using the `mean` attribute of the `var` attribute instead of the result of `withReplicates`.

By the way, this author is using normal distribution instead of t distribution to compute confidence intervals. My feeling is that t distribution is probably better. 

I will prepare a pull request to add this Warning message.

In addition, I will prepare two additional PR if it suits you: (i) a svyclm function (using wR it's really easy) and (ii) a tidy method for `svrepstatmisc`  class (I'm using `broom` package quite a lot).

**Comment by larmarange** [comment]
integrated in https://github.com/carlganz/svrepmisc/pull/7/
